apiVersion: apps/v1
kind: Deployment
metadata:
  name: HealthCareApp-deployment
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: HealthCareApp-deployment
        image: mehooman/HealthCare:v1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: HealthCareApp-Service
spec:
  type: NodePort
  selector:
    app: healthcare-app
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8082
    nodePort: 30083  # NodePort value; it will expose the service on this port
